# train_path: "C:/Users/penda/Desktop/Workspace/My_Projects/U-NetR/erythrocyte_data_multi/train"
# val_path: "C:/Users/penda/Desktop/Workspace/My_Projects/U-NetR/erythrocyte_data_multi/val"

train_path: "/work/c-2iia/sp165339/Sickle_Cell_Segmentation/erythrocyte_data_multi/train"
val_path: "/work/c-2iia/sp165339/Sickle_Cell_Segmentation/erythrocyte_data_multi/val"
